[package]
name = "calculator_app"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
meval = "0.2.0"
